### Phase II
#### Hypothesis: How does the amount of sleep (different hours) affect the average college student in terms of productivity (freshman or senior)?

##### Installing pandas

In [4]:
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

#### Dataset #1

In [5]:
cmu_sleep = "https://raw.githubusercontent.com/samira-maria/2950Project/refs/heads/main/CSVs/CourseGrades(3-6-20).csv"
df = pd.read_csv(cmu_sleep)
df.head()

   egoid  AcademicPeriod  CourseReferenceNumber FinalGrade
0  92552          201520                  26443         A-
1  92552          201520                  30358          A
2  92552          201610                  20712          B
3  92552          201710                  21026          A
4  92552          201510                  11726          B

#### Dataset #2

In [2]:
coursegrades = "https://raw.githubusercontent.com/samira-maria/2950Project/refs/heads/main/CSVs/CourseGrades(3-6-20).csv"
df = pd.read_csv(coursegrades)
df.head()

   egoid  AcademicPeriod  CourseReferenceNumber FinalGrade
0  92552          201520                  26443         A-
1  92552          201520                  30358          A
2  92552          201610                  20712          B
3  92552          201710                  21026          A
4  92552          201510                  11726          B

#### Dataset #3

In [6]:
fitbitsleep = "https://raw.githubusercontent.com/samira-maria/2950Project/refs/heads/main/CSVs/FitbitSleep(1-30-20).csv"
df = pd.read_csv(fitbitsleep)
df.head()

,egoid,dataDate,timetobed,timeoutofbed,bedtimedur,minstofallasleep,minsafterwakeup,minsasleep,minsawake,Efficiency
0,44869,2015-07-28,06:25:00,10:27:00,243,0,0,232,11,0.954733
1,44869,2015-07-29,03:26:30,07:21:30,236,1,4,216,15,0.935065
2,44869,2015-07-29,12:03:30,16:44:30,282,3,0,267,12,0.956989
3,44869,2015-07-30,06:27:30,14:31:30,485,4,0,451,30,0.937630
4,44869,2015-07-31,04:40:30,06:27:30,108,0,0,100,8,0.925926